spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5555/postgres
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://localhost:8888
logging:
  level:
    org:
      springframework:
        security: TRACE
service:
  key: Uieiej6895op
GATEWAY_URL_BASE: ""