spring:
  application:
    name: 'service-db-store'
  r2dbc:
    url: r2dbc:postgresql://localhost:5555/micro_chats
    password: postgres
    username: postgres
  cloud:
    function:
      definition: getMessage
    stream:
      bindings:
#        processMessage-in-0:
#          destination: my-queue
#          group: key
#        processMessage-out-1:
#          destination: my-queue
#          group: key
        getMessage-in-0:
          destination: input
          group: create
      rabbit:
        bindings:
#          processMessage-in-0:
#            consumer:
#              exchange-type: topic
#          processMessage-out-1:
#            producer:
#              exchange-type: topic
          getMessage-in-0:
            consumer:
              exchange-type: topic
grpc:
  client:
    message:
      address: localhost:9090
      negotiation-type: plaintext
server:
  port: 8082