spring:
  config:
    import: optional:configserver:http://localhost:8888/
  profiles:
    active: dev
  application:
    name: 'micro-chats-data'

server:
  port: 8080
  error:
    include-message: always
