spring:
  application:
    name: 'micro-chats'
  config:
    import: optional:configserver:http://localhost:8888/
  profiles:
    active: dev
  error:
    include-message: always
  rabbitmq:
    port: 5672
    username: guest
    password: guest
  cloud:
    function:
      definition: testUserGet
    stream:
      bindings:
        processMessage-in-0:
          destination: my-queue
          group: key
        processMessage-out-1:
          destination: my-queue
          group: key
      rabbit:
        bindings:
          processMessage-in-0:
            consumer:
              exchange-type: topic
          processMessage-out-1:
            producer:
              exchange-type: topic

logging:
  level:
    org.springframework.security: trace
service:
  key: Uieiej6895op