spring:
  application:
    name: 'micro-data'
  config:
    import: optional:configserver:http://localhost:8888/
  profiles:
    active: dev

server:
  port: 8080
  error:
    include-message: always
