spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5555/micro_chats
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8888/
