spring:
  application:
    name: 'micro-chats'
  config:
    import: configserver:http://localhost:8888/
  profiles:
    active: dev
  error:
    include-message: always
logging:
  level:
    org.springframework.security: trace
service:
  key: Uieiej6895op